### ISSUE TITLE
Whats the right way to store backend specific data associated w/ an endpoint?

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/kpng#278]
I wrote up a question here https://jayunit100.blogspot.com/2022/04/serviceinfo-structs-in-kube-proxy.html

which i ran into when i needed the hnsID stored in the KPNG v1locanet.Endpoint object.

Whats the right way to, for examples, store the HNS ID when using SetService/SetEndpoint implementations, and in general , to cache backend specific data for an endpoint ?

**Comment by mcluseau** [comment]
you know I'm going to say it's a no-brainer with fullstate+diffstore2 approach right? :rofl: 
The diffstore will store the state you want, and you'll get the extra bonus of being able to have an arbitrary number of values for each kpng object, like multiple HNS IDs for each endpoint. And I given your blog post, it looks like you'll multiple HNS IDs per endpoint, since you'll have one for each port to map.

**Comment by jayunit100** [comment]
i guess your right, we could leverage the diffstore for all the extra metadata
