### ISSUE TITLE
Use separate containers for source and sink

### ISSUE THREAD

**Issue by therealak12** [kubernetes-sigs/kpng#471]
If I've understood correctly, the daemonset currently contains only a single container which runs 2 jobs, e.g. one watching the API-Server and the other applying IPTables rules. In order to enhance clarity and improve readability, it may be beneficial to split these tasks into two separate containers.

**Comment by jayunit100** [comment]
Hi! Is this for dev? 

If you look at the kpng local up script we run them as separate processes 

But maybe there's some ways we can make that local up script more human usable like writing it as a go program .... with command line options that indicate the choice you suggested ? 

Otherwise maybe we can maybe use YTT as a user facing way to configure different deployments for production scenarios

**Comment by jayunit100** [comment]
Hi! Is this for dev? 

If you look at the kpng local up script we run them as separate processes 

But maybe there's some ways we can make that local up script more human usable like writing it as a go program .... with command line options that indicate the choice you suggested ? 

Otherwise maybe we can maybe use YTT as a user facing way to configure different deployments for production scenarios ? 

Or let me know if you had something else in mind

**Comment by therealak12** [comment]
Hi.
Thanks for your fast response!
I used `make tilt-setup` and `make tilt-up` to deploy the daemonset on a local KinD cluster, the result was a daemonset with a single container running both processes, i.e. `to-local` and `to-iptables`. Running two containers could be better IMHO :-?

**Comment by therealak12** [comment]
I think I've misunderstood the architecture. Closing the issue.
