### ISSUE TITLE
Makefile, multistage builds?

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/kpng#59]
We'll need to make a makefile that supports:
- building 
- publishing containers to a registry
- building at least some subset of binaries
- setup modd  (use modd under the hood)

per @uablrek lets keep it simple :) NO GRADLE and no https://taskfile.dev/#/

**Comment by jayunit100** [comment]
in general , targets would be
`make test` -> run all the unit tests
`make docker` -> builds a docker image of kpng
`make up` -> runs the full kpng-local-up.sh
`make static` -> compiles kpng executable binaries

as a starting point, looking at how we do hack/kpng-local-up and decomposing those parts into separate make tasks might be a good way to get started here

**Comment by uablrek** [comment]
Since there will be very few dependencides (or none at all), "make" is not the tool. A script is easier to maintain. The only reason to use make is that many people expects it. A reason as good as any but large scripts-in-a-makefile looks bad (to put it nicely). I would suggest a "build" script or a "build/" directory with some scripts and a Makefile that just calls them, like;
```
.PHONY: test docker up static
test docker up static:
        ./build/$@
```

**Comment by jayunit100** [comment]
I think we can close this
